# This file generates the GitHub Actions matrix.
# Traditional split keyboard setup - left half acts as central, right as peripheral
---
include:
  # Sofle left half (central/master)
  - board: nice_nano_v2
    shield: sofle_left

  # Sofle right half (peripheral)
  - board: nice_nano_v2
    shield: sofle_right

  # Settings reset firmware (flash this first on both halves)
  - board: nice_nano_v2
    shield: settings_reset
